### ISSUE TITLE
Please collect the .zip file in one addon folder

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [19829984/Blender_Sync_Viewport#5]
If works as now
It will be installed to the root folder of blender addon
So blender can't read the addon and load it
You should make a new folder
![image](https://user-images.githubusercontent.com/65578116/230922366-ef647ee8-316a-4884-a666-8567ee8a3857.png)

zip file is wrong

![image](https://user-images.githubusercontent.com/65578116/230922513-bc4187f6-e501-4d11-b977-d376c1c34e0a.png)

just do it

![image](https://user-images.githubusercontent.com/65578116/230923074-14658394-701a-48ae-90d3-8696ab1eebbd.png)

**Comment by 19829984** [comment]
Ahh I'm sorry about that, I didn't notice this mistake. Will update.

**Comment by 19829984** [comment]
Release 1.0.2 is now collected under one addon folder. I won't do this for the previous releases since they have a major bug that prevents them from working properly anyway. Thanks for raising this issue.
