### ISSUE TITLE
Crash when using clipping region

### ISSUE THREAD

**Issue by Jauhuaj** [19829984/Blender_Sync_Viewport#7]
If 2 viewports are synced, using clipping region(alt+b) and entering edit mode causes blender to crash.

[blender.crash.txt](https://github.com/user-attachments/files/16096957/blender.crash.txt)

**Comment by 19829984** [comment]
Thanks for reporting this issue. Life has been a bit busy lately so I'm not sure when I'll have the time to fix it, but it's on the todo list.

**Comment by 19829984** [comment]
Sorry that I have never gotten around to directly addressing this issue, however in Blender 4.3 it no longer crashes when using clipping region and entering edit mode. I will close this for now unless someone has a need for it for prior versions.
